server/products/urls.py
from django.urls import path
from .views import detail_view, list_view

app_name = 'products'

urlpatterns = [
    path('', list_view, name='products'),
    path('<int:pk>/', detail_view, name='detail'),
]

server/products/models.py
from django.db import models

# НФ3

# Класс категории продукта
class CategoryProduct(models.Model):
    # поле с первичным ключем создается автоматически
    # Название категории товара
    name = models.CharField(max_length=128, verbose_name='имя категории товара')
    # Возможное написание категории
    alias_name = models.CharField(max_length=128, blank=True)

    def __str__(self):
        return self.name


# Класс типа продукта
class ProductType(models.Model):
    # поле с первичным ключем создается автоматически
    # Название типа продукта
    name = models.CharField(max_length=128, verbose_name='тип продукта')
    # Возможное написание типа товара
    alias_name = models.CharField(max_length=128, blank=True)

    def __str__(self):
        return self.name


# Класс бренда
class BrandProduct(models.Model):
    # поле с первичным ключем создается автоматически
    # Название бренда
    name = models.CharField(max_length=128, verbose_name='Имя бренда')
    # Возможное написание бренда
    alias_name = models.CharField(max_length=128, blank=True)

    def __str__(self):
        return self.name


# Класс продуктов.
class Product(models.Model):
    # поле с первичным ключем создается автоматически (ID продукта, артикул)
    # Заголовок продукта
    title = models.CharField(max_length=255, verbose_name='имя продукта')
    # Краткое описание товара
    short_desc = models.CharField(
        max_length=128,
        blank=True,
        verbose_name='краткое описание'
    )
    # Подробное описание товара
    description = models.TextField(verbose_name='подробно', blank=True)
    # ID бренда из class BrandProduct
    brand_id = models.ForeignKey(BrandProduct, on_delete=models.CASCADE)
    # ID типа продукта из class ProductType
    product_type_id = models.ForeignKey(
        ProductType,
        on_delete=models.CASCADE
    )
    # ID из категории товара class CategoryProduct
    category_id = models.ForeignKey(
        CategoryProduct,
        on_delete=models.CASCADE
    )
    # стоимость продукта
    price = models.DecimalField(
        max_digits=10,
        decimal_places=1,
        verbose_name='цена',
        default=0
    )
    # картинки товара большая и 3 дополнительные
    img_big = models.ImageField(
        upload_to='big_img',
        blank=True
    )
    img_s_1 = models.ImageField(
        upload_to='small_img_1',
        blank=True
    )
    img_s_2 = models.ImageField(
        upload_to='small_img_2',
        blank=True
    )
    img_s_3 = models.ImageField(
        upload_to='small_img_3',
        blank=True
    )

    def __str__(self):
        return "{} ({})".format(self.title, self.category_id.name)


# Класс карточки заказа
# class Order(models.Model):
    # поле с первичным ключем создается автоматически
    # Имя заказчика
    # user_name = models.CharField(max_length=128, verbose_name='Имя заказчика')
    # Телефон заказчика
    # phone = models.CharField(max_length=32, verbose_name='телефон заказчика')
    # datatime =  models.DateTimeField(auto_now_add=True)


# Класс заказа товара
# class ProductOrder(models.Model):
    # order_id =  # ID заказа продукта
    # product_id =  # ID заказанного продукта
    # count =  # счет

server/products/views.py
from django.shortcuts import render, get_list_or_404, get_object_or_404
import json
from .models import CategoryProduct, Product


def list_view(request):
    return render(request, 'products/list.html', {'products': get_list_or_404(Product)})


def detail_view(request, pk):
    return render(request, 'products/detail.html', {'object': Product.objects.get(id=pk)})

server/products/templates/products/detail.html
{% extends 'master.html' %}
{% load staticfiles %}

{% block page_title %}
Купить недорого {{ object.title }}
{% endblock%}

{% block page_content %}

  {% if object %}
        <div class="menu-link">
          <div class="prod-menu">
            <ul>
              <li><a href="#">All</a></li>
              <li><a href="#">Home</a></li>
              <li><a href="#">Office</a></li>
              <li><a href="#">Furniture</a></li>
              <li><a href="#">Modern</a></li>
              <li><a href="#">Classic</a></li>
            </ul>
          </div>
        </div>

        <div class="prod-deails">
          <div class="img-deails">
            <a href="{{ object.img_big.url }}" target="_blank"><img src="{{ object.img_big.url }}" alt=""></a>
            <div class="controll">
              <a href="#"><img src="{{ object.img_s_1.url }}" alt="" class="active"></a>
              <a href="#"><img src="{{ object.img_s_2.url }}" alt="" class="active"></a>
              <a href="#"><img src="{{ object.img_s_3.url }}" alt="" class="active"></a>
            </div>
          </div>
          <div class="txt-deails">
            <h2>{{ object.title }}</h2>
            <h3>Hot deal</h3>
            <p class="price">&#x20bd; <span>{{ object.price }}</span></p>
            <a href="#">Купить</a>
            <p class="full-txt">{{ object.description }}</p>
          </div>
        </div>
      {% else %}
      <h3 style="text-align: center; padding-top: 100px;">Product does not exists</h3>
  {% endif %}

{% endblock %}

server/products/templates/products/list.html
{% extends 'master.html' %}
{% load staticfiles %}


{% block page_title %}
Эксклюзивная мебель в Москве. Звоните в любое время дня и ночи.
{% endblock%}

{% block page_content %}


    <div class="all-products">
      <div class="prod-menu">
        <ul>
          <li id="underscore"><a href="#">All</a></li>
          <li id="underscore"><a href="#">Home</a></li>
          <li id="underscore"><a href="#">Office</a></li>
          <li><a href="#">Furniture</a></li>
          <li><a href="#">Modern</a></li>
          <li><a href="#">Classic</a></li>
        </ul>
      </div>

        <div class="prod-link">
          {% for el in products %}
          <a href="{% url 'products:detail' pk=el.id %}"><img src="{{ el.img_big.url }}" alt="{{ el.short_desc }}" width="370px" alt=""></a>
          {% endfor %}
        </div>



      <div class="reload">
        <img src="/static/img/reload.svg" alt="">
      </div>

    </div>

    <div class="promo-product">
      <div class="promo-content-1">
        <div class="text-block">
          <h3>Exclusive</h3>
          <h1>Fishnet&nbsp;Chair</h1>
          <p>Seat and back with upholstery made of cold cure foam. Steel frame, available in 	matt</p>
          <a href="/product-deails/">Order us</a>
        </div>
      </div>
      <div class="promo-content-2">
        <div class="text-block">
          <h3>Exclusive</h3>
          <h1>Fishnet&nbsp;Chair</h1>
          <p>Seat and back with upholstery made of cold cure foam. Steel frame, available in 	matt</p>
          <a href="/product-deails/">Order us</a>
        </div>
      </div>
    </div>


{% endblock %}