server/authapp/urls.py
from django.urls import path
from .views import login_view


app_name = 'authapp'


urlpatterns = [
    path('', login_view, name='login')
]

server/authapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class ShopUser(AbstractUser):
    avatar = models.ImageField(
        upload_to='user_avatars',
        blank=True,
        null=True
    )
    age = models.PositiveIntegerField(
        verbose_name='возраст',
        blank=True,
        null=True
    )

    def __str__(self):
        return self.username

server/authapp/forms.py
from django import forms


class LoginForm(forms.Form):
    username = forms.CharField(
        label='Login',
        max_length=150,
        widget=forms.widgets.TextInput(
            attrs={
                        'class': 'field field-login'
                    }
        )
    )
    password = forms.CharField(
        max_length=72,
        widget=forms.widgets.PasswordInput(
            attrs={
                        'class': 'field field-password'
                    }
        )
    )

server/authapp/views.py
from django.shortcuts import render

from .forms import LoginForm

def login_view(request):
    form = LoginForm
    
    return render(
        request,
        'authapp/login.html',
        {
            'form': form
        }
    )

server/authapp/templates/authapp/login.html
{% extends 'master.html' %}
{% load staticfiles %}

{% block page_content %}

  {% if form.errors %}
      <h3 style="text-align: center; padding-top: 100px;">Ошибка!</h3>
       <p>Имя пользователя или пароль не совпадают. Пожайлуста, попробуйте еще раз</p>
  {% endif %}

  {% if next %}
    {% if user.is_authenticated %}
    <p>Ваша учетная запись не имеет доступа к данному разделу. Для продолжения,
       войдите под той учетной записью, которая имеет доступ.</p>
    {% else %}
    <p>Пожайлуста войдите, чтобы увидить содержимое данной страницы.</p>
    {% endif %}
  {% endif %}

  <h3 style="text-align: center; padding-top: 100px;">Войдите</h3>
    <form class="" action="{% url 'authapp:login' %}" method="post">
      {% csrf_token %}
      {% for field in form %}
        <div class="field-group">
          <label for="{{ field.name }}">{{ field.label }}</label>
          {{ field }}
        </div>
      {% endfor %}
      <input type="submit" class='field-submit' name="" value="Войти">
    </form>
    {# {% url 'password_resset' %} #}
    <p><a href="#">Забыли пароль?</a></p>
{% endblock %}